services:
  vite-react:
    container_name: mui-stacks-dev
    image: node:18
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: tail -f /dev/null  # Keep the container running
